# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pendulum/mainwindow.ui'
#
# Created: Wed Jul 18 17:17:34 2012
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.angle_plot = MatplotlibWidget(self.centralwidget)
        self.angle_plot.setObjectName("angle_plot")
        self.gridLayout_2.addWidget(self.angle_plot, 1, 0, 1, 3)
        self.connect_button = QtGui.QPushButton(self.centralwidget)
        self.connect_button.setMaximumSize(QtCore.QSize(100, 16777215))
        self.connect_button.setObjectName("connect_button")
        self.gridLayout_2.addWidget(self.connect_button, 3, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 3, 1, 1, 1)
        self.angle_label = QtGui.QLabel(self.centralwidget)
        self.angle_label.setMinimumSize(QtCore.QSize(200, 0))
        self.angle_label.setObjectName("angle_label")
        self.gridLayout_2.addWidget(self.angle_label, 3, 2, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 2, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem1 = QtGui.QSpacerItem(20, 85, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.record_button = QtGui.QPushButton(self.groupBox_2)
        self.record_button.setObjectName("record_button")
        self.verticalLayout_2.addWidget(self.record_button)
        self.gridLayout.addWidget(self.groupBox_2, 1, 1, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(300, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.zero_button = QtGui.QPushButton(self.groupBox)
        self.zero_button.setObjectName("zero_button")
        self.horizontalLayout.addWidget(self.zero_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.motor_control = QtGui.QSlider(self.groupBox)
        self.motor_control.setMinimum(-127)
        self.motor_control.setMaximum(127)
        self.motor_control.setOrientation(QtCore.Qt.Horizontal)
        self.motor_control.setTickPosition(QtGui.QSlider.TicksBelow)
        self.motor_control.setObjectName("motor_control")
        self.horizontalLayout_2.addWidget(self.motor_control)
        self.motor_control_sb = QtGui.QSpinBox(self.groupBox)
        self.motor_control_sb.setMinimumSize(QtCore.QSize(75, 0))
        self.motor_control_sb.setMaximumSize(QtCore.QSize(75, 16777215))
        self.motor_control_sb.setMinimum(-127)
        self.motor_control_sb.setMaximum(127)
        self.motor_control_sb.setObjectName("motor_control_sb")
        self.horizontalLayout_2.addWidget(self.motor_control_sb)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.desired_position = QtGui.QSlider(self.groupBox)
        self.desired_position.setMaximum(360)
        self.desired_position.setOrientation(QtCore.Qt.Horizontal)
        self.desired_position.setTickPosition(QtGui.QSlider.TicksBelow)
        self.desired_position.setObjectName("desired_position")
        self.horizontalLayout_3.addWidget(self.desired_position)
        self.desired_pendulum_sb = QtGui.QDoubleSpinBox(self.groupBox)
        self.desired_pendulum_sb.setMinimumSize(QtCore.QSize(75, 0))
        self.desired_pendulum_sb.setMaximumSize(QtCore.QSize(75, 16777215))
        self.desired_pendulum_sb.setMaximum(359.99)
        self.desired_pendulum_sb.setSingleStep(1.0)
        self.desired_pendulum_sb.setObjectName("desired_pendulum_sb")
        self.horizontalLayout_3.addWidget(self.desired_pendulum_sb)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.doubleSpinBox = QtGui.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout_3.addWidget(self.doubleSpinBox, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.doubleSpinBox_4 = QtGui.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.gridLayout_6.addWidget(self.doubleSpinBox_4, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout_6.addWidget(self.label_6, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_6)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.doubleSpinBox_5 = QtGui.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_5.setObjectName("doubleSpinBox_5")
        self.gridLayout_7.addWidget(self.doubleSpinBox_5, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout_7.addWidget(self.label_7, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_7)
        self.pushButton = QtGui.QPushButton(self.groupBox)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.gridLayout.addWidget(self.groupBox, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.motor_control, QtCore.SIGNAL("valueChanged(int)"), self.motor_control_sb.setValue)
        QtCore.QObject.connect(self.motor_control_sb, QtCore.SIGNAL("valueChanged(int)"), self.motor_control.setValue)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.connect_button.setText(QtGui.QApplication.translate("MainWindow", "Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.angle_label.setText(QtGui.QApplication.translate("MainWindow", "Pendulum angle: 0", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Record", None, QtGui.QApplication.UnicodeUTF8))
        self.record_button.setText(QtGui.QApplication.translate("MainWindow", "Record", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Control", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Motor Control", None, QtGui.QApplication.UnicodeUTF8))
        self.zero_button.setText(QtGui.QApplication.translate("MainWindow", "Zero", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Desired Pendulum Position", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "P", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "I", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "D", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "Control", None, QtGui.QApplication.UnicodeUTF8))

from matplotlibwidget import MatplotlibWidget
